name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    uses: ectobit/reusable-workflows/.github/workflows/go-check.yaml@main
    with:
      lint-command: make lint
      test-command: make test
